'use strict';

const { parseChecklistStats } = require('./governed-artifacts.cjs');
const { parseReviewMarkdown } = require('./trust-helpers.cjs');
const { buildUiArchivePolicy } = require('./ui-archive-policy.cjs');

/**
 * Builds a human-readable handoff report from already-loaded feature artifacts.
 *
 * @param {{
 *   feature: string,
 *   version: string,
 *   now?: string,
 *   archived?: boolean,
 *   specContent?: string|null,
 *   promptReceiptContent?: string|null,
 *   verifyContent?: string|null,
 *   verifyReceipt?: Record<string, any>|null,
 *   planContent?: string|null,
 *   reviewContent?: string|null,
 *   uiReviewReceipt?: Record<string, any>|null,
 *   state?: { error_count?: number, error_history?: string[] }
 * }} input
 * @returns {string}
 */
function generateHandoffReportContent(input) {
    const feature = input.feature;
    const version = input.version;
    const specContent = input.specContent || null;
    const promptReceiptContent = input.promptReceiptContent || null;
    const verifyContent = input.verifyContent || null;
    const verifyReceipt = input.verifyReceipt || null;
    const planContent = input.planContent || null;
    const reviewContent = input.reviewContent || null;
    const uiReviewReceipt = input.uiReviewReceipt || null;
    const archived = !!input.archived;
    const state = input.state || {};
    const checklist = planContent ? parseChecklistStats(planContent) : null;
    const uiArchivePolicy = buildUiArchivePolicy(uiReviewReceipt, {
        deepRequested: !!verifyReceipt?.deepRequested,
    });

    let report = `# Handoff Report: ${feature}\n\n`;
    report += `**Completed:** ${input.now || new Date().toISOString()}\n`;
    if (archived) report += `**Status:** Archived\n`;
    report += `**Generated by:** steroid-workflow v${version}\n\n`;

    report += `## What Was Built\n\n`;
    if (specContent) {
        const criteria = specContent.match(/(?:Given|When|Then|Scenario).+/gi) || [];
        if (criteria.length > 0) {
            report += `${criteria.length} acceptance criteria recorded in spec.md:\n\n`;
            for (const c of criteria.slice(0, 10)) report += `- ${c.trim()}\n`;
            if (criteria.length > 10) report += `- _(and ${criteria.length - 10} more)_\n`;
        } else {
            report += '_See spec.md for full acceptance criteria._\n';
        }
    } else {
        report += '_No spec.md found._\n';
    }

    if (reviewContent) {
        const review = parseReviewMarkdown(reviewContent);
        report += `\nImplementation evidence review:\n\n`;
        report += `- Stage 1 (Spec): ${review.stage1}\n`;
        report += `- Stage 2 (Quality): ${review.stage2}\n`;
    }

    report += `\n## What Was Tested\n\n`;
    if (verifyContent) {
        const statusMatch = verifyContent.match(/\*\*Status:\*\* (PASS|FAIL|CONDITIONAL)/);
        const scoreMatch = verifyContent.match(/\*\*Spec Score:\*\* (.+)/);
        report += `**Status:** ${statusMatch ? statusMatch[1] : 'Unknown'}\n`;
        if (scoreMatch) report += `**Score:** ${scoreMatch[1]}\n`;
        const testMatch = verifyContent.match(/\*\*Result:\*\* (.+)/);
        if (testMatch) report += `**Tests:** ${testMatch[1]}\n`;
    } else {
        report += '_No verify.md found._\n';
    }

    report += `\n## Prompt Interpretation\n\n`;
    if (promptReceiptContent) {
        try {
            const promptReceipt = JSON.parse(promptReceiptContent);
            report += `- Primary Intent: ${promptReceipt.primaryIntent || 'Unknown'}\n`;
            if (Array.isArray(promptReceipt.secondaryIntents) && promptReceipt.secondaryIntents.length > 0) {
                report += `- Secondary Intents: ${promptReceipt.secondaryIntents.join(', ')}\n`;
            }
            report += `- Continuation State: ${promptReceipt.continuationState || 'Unknown'}\n`;
            report += `- Complexity: ${promptReceipt.complexity || 'Unknown'}\n`;
            report += `- Ambiguity: ${promptReceipt.ambiguity || 'Unknown'}\n`;
            report += `- Recommended Route: ${promptReceipt.recommendedPipeline || 'Unknown'}\n`;
        } catch {
            report += '_prompt.json found but could not be parsed._\n';
        }
    } else {
        report += '_No prompt receipt captured._\n';
    }

    report += `\n## Review Status\n\n`;
    if (reviewContent) {
        const review = parseReviewMarkdown(reviewContent);
        report += `- Spec Review: ${review.stage1}\n`;
        report += `- Quality Review: ${review.stage2}\n`;
    } else {
        report += '_No two-stage review performed._\n';
    }

    report += `\n## Tasks Completed\n\n`;
    if (checklist) {
        report += `${checklist.done}/${checklist.total} tasks completed (${checklist.percent}%)\n`;
    } else {
        report += '_No plan.md found._\n';
    }

    report += `\n## Known Limitations\n\n`;
    if (checklist) {
        if (checklist.deferred.length > 0) {
            report += `${checklist.deferred.length} items were not completed:\n\n`;
            for (const d of checklist.deferred.slice(0, 5)) report += `${d}\n`;
            if (checklist.deferred.length > 5) report += `- _(and ${checklist.deferred.length - 5} more)_\n`;
        } else {
            report += 'All planned tasks were completed.\n';
        }
    } else {
        report += '_Unknown — no plan.md available._\n';
    }

    report += `\n## Build Health\n\n`;
    report += `- Circuit breaker errors during build: ${state.error_count || 0}\n`;
    if (state.error_history && state.error_history.length > 0) {
        report += '- Errors encountered:\n';
        for (const err of state.error_history.slice(-5)) report += `  - ${err}\n`;
    }

    if (uiReviewReceipt) {
        report += `\n## Frontend Quality\n\n`;
        report += `- UI Review Status: ${uiReviewReceipt.status || 'Unknown'}\n`;
        report += `- Verification Status: ${uiReviewReceipt.verifyStatus || 'Unknown'}\n`;
        report += `- Frontend Release Recommendation: ${uiArchivePolicy.recommendation}\n`;
        report += `- Stack: ${uiReviewReceipt.stack || 'Unknown'}\n`;
        report += `- Wrapper Skill: ${uiReviewReceipt.wrapperSkill || 'none'}\n`;
        report += `- Refreshed By: ${uiReviewReceipt.freshness?.source || 'unknown'}\n`;
        report += `- Refresh Reason: ${uiReviewReceipt.freshness?.reason || 'Unknown'}\n`;
        if (uiReviewReceipt.generatedAt) {
            report += `- UI Review Generated: ${uiReviewReceipt.generatedAt}\n`;
        }
        if (uiReviewReceipt.freshness?.evidenceUpdatedAt) {
            report += `- Latest Frontend Evidence: ${uiReviewReceipt.freshness.evidenceUpdatedAt}\n`;
        }
        if (uiReviewReceipt.freshness?.evidenceUpdatedFrom) {
            report += `- Latest Evidence Source: ${uiReviewReceipt.freshness.evidenceUpdatedFrom}\n`;
        }
        if (uiReviewReceipt.previewTarget) {
            report += `- Preview Target: ${uiReviewReceipt.previewTarget}\n`;
        }
        report += `- Policy Summary: ${uiArchivePolicy.summary}\n`;
        const findings = Array.isArray(uiReviewReceipt.findings) ? uiReviewReceipt.findings : [];
        if (findings.length > 0) {
            report += '\nTop frontend findings:\n';
            for (const finding of findings.slice(0, 5)) {
                report += `- ${String(finding.severity || 'info').toUpperCase()}: ${finding.title || 'Untitled'}${
                    finding.detail ? ` — ${finding.detail}` : ''
                }\n`;
            }
        } else {
            report += '- No significant frontend risks were recorded.\n';
        }
        if (uiArchivePolicy.blockReasons.length > 0) {
            report += '\nFrontend policy blockers:\n';
            for (const reason of uiArchivePolicy.blockReasons) {
                report += `- ${reason}\n`;
            }
            if (uiArchivePolicy.overrideFlag) {
                report += `- Override available: ${uiArchivePolicy.overrideFlag}\n`;
            }
        } else if (uiArchivePolicy.warnReasons.length > 0) {
            report += '\nFrontend policy cautions:\n';
            for (const reason of uiArchivePolicy.warnReasons) {
                report += `- ${reason}\n`;
            }
        }
    }

    report += `\n---\n\n_Generated by steroid-workflow v${version} handoff system_\n`;
    return report;
}

module.exports = {
    generateHandoffReportContent,
};
