'use strict';

function formatPromptMarkdown(feature, analysis, sessionState) {
    const lines = [
        `# Prompt Brief: ${feature}`,
        '',
        `**Captured:** ${new Date().toISOString()}`,
        `**Source:** normalize-prompt`,
        '',
        '## Summary',
        '',
        `- Raw Prompt: ${analysis.rawPrompt || 'None'}`,
        `- Normalized Summary: ${analysis.normalizedSummary || 'None'}`,
        `- Primary Intent: ${analysis.primaryIntent || 'Unknown'}`,
        `- Secondary Intents: ${analysis.secondaryIntents.length > 0 ? analysis.secondaryIntents.join(', ') : 'None'}`,
        `- Continuation State: ${analysis.continuationState || 'Unknown'}`,
        `- Complexity / Risk: ${analysis.complexity || 'Unknown'} / ${analysis.risk || 'Unknown'}`,
        `- Ambiguity: ${analysis.ambiguity || 'Unknown'}`,
        `- Recommended Route: ${analysis.recommendedPipeline || 'Unknown'}`,
        `- Pipeline Hint: ${analysis.pipelineHint || 'Unknown'}`,
        '',
        '## Assumptions',
        '',
    ];

    if (analysis.assumptions.length > 0) {
        for (const assumption of analysis.assumptions) {
            lines.push(`- ${assumption}`);
        }
    } else {
        lines.push('- None captured.');
    }

    lines.push('', '## Non-Goals', '');
    if (analysis.nonGoals.length > 0) {
        for (const nonGoal of analysis.nonGoals) {
            lines.push(`- ${nonGoal}`);
        }
    } else {
        lines.push('- None captured.');
    }

    lines.push('', '## Unresolved Questions', '');
    if (analysis.unresolvedQuestions.length > 0) {
        for (const question of analysis.unresolvedQuestions) {
            lines.push(`- ${question}`);
        }
    } else {
        lines.push('- None captured.');
    }

    lines.push('', '## Session Context', '');
    lines.push(`- Active Feature: ${sessionState.activeFeature || 'None'}`);
    lines.push(`- Default State: ${sessionState.defaultState || 'Unknown'}`);
    lines.push(
        `- Known Features: ${
            sessionState.knownFeatures && sessionState.knownFeatures.length > 0
                ? sessionState.knownFeatures.join(', ')
                : 'None'
        }`,
    );
    lines.push(`- Circuit State: ${sessionState.recoveryState || 'active'} (${sessionState.errorCount || 0} errors)`);

    if (analysis.splitRecommended && analysis.suggestedFeatures.length > 0) {
        lines.push('', '## Suggested Split', '');
        for (const item of analysis.suggestedFeatures) {
            lines.push(`- ${item}`);
        }
    }

    lines.push('', '_Generated by steroid-workflow prompt intelligence._', '');
    return lines.join('\n');
}

module.exports = {
    formatPromptMarkdown,
};
